import { Item } from './types';

export const mockItems: Item[] = [
  {
    id: '1',
    title: 'Casio FX-991ES Calculator',
    description: 'Barely used, all functions working. Perfect for engineering courses.',
    price: 450,
    category: 'stationery',
    condition: 'like-new',
    imageUrl: 'https://images.unsplash.com/photo-1587145820266-a5951ee6f620?w=400',
    sellerName: 'Raj Patel',
    sellerRating: 4.8,
    createdAt: '2026-08-05',
  },
  {
    id: '2',
    title: 'Data Structures Textbook',
    description: 'Cormen 3rd edition, minimal highlighting, great condition.',
    price: 600,
    category: 'books',
    condition: 'used',
    imageUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400',
    sellerName: 'Priya Shah',
    sellerRating: 4.9,
    createdAt: '2026-08-04',
  },
  {
    id: '3',
    title: 'Lab Coat (Size M)',
    description: 'Used for one semester only, washed and clean.',
    price: 150,
    category: 'clothing',
    condition: 'used',
    imageUrl: 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?w=400',
    sellerName: 'Arjun Mehta',
    sellerRating: 4.7,
    createdAt: '2026-08-03',
  },
  {
    id: '4',
    title: 'Arduino Uno + Breadboard Kit',
    description: 'Complete IoT starter kit, used for one project only.',
    price: 800,
    category: 'electronics',
    condition: 'like-new',
    imageUrl: 'https://images.unsplash.com/photo-1608564697071-ddf911d81370?w=400',
    sellerName: 'Sneha Joshi',
    sellerRating: 5.0,
    createdAt: '2026-08-02',
  },
];